import * as DocumentPicker from 'expo-document-picker';
import * as FileSystem from 'expo-file-system/legacy';
import * as XLSX from 'xlsx';

export interface PickedFileData {
  name: string;
  /** All parsed rows with normalized column keys. */
  rows: Record<string, unknown>[];
  /** Column names used in the rows. May be `col_1, col_2, …` for header-less files. */
  headers: string[];
  /** Whether the file had real headers (true) or we generated `col_N`. */
  hasHeaders: boolean;
  /** Compact textual preview (sample) for the AI to read. */
  preview: string;
  totalRows: number;
}

const EMPTY_HEADER_PATTERN = /^__EMPTY/i;

function looksLikeRealHeaders(headers: string[]): boolean {
  if (headers.length === 0) return false;
  // If most headers are XLSX's `__EMPTY_N` autogenerated placeholders, treat as header-less.
  const placeholderCount = headers.filter((h) => EMPTY_HEADER_PATTERN.test(h)).length;
  if (placeholderCount > headers.length / 2) return false;
  // Otherwise, require at least one Arabic or Latin word longer than 1 char.
  return headers.some((h) => /[A-Za-z؀-ۿ][A-Za-z؀-ۿ]/.test(h));
}

/** Pick an Excel/CSV file and parse it into a compact form for the AI. */
export async function pickFileForAI(): Promise<PickedFileData | null> {
  const res = await DocumentPicker.getDocumentAsync({
    type: [
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'application/vnd.ms-excel',
      'text/csv',
      '*/*',
    ],
    copyToCacheDirectory: true,
    multiple: false,
  });
  if (res.canceled || !res.assets?.[0]) return null;
  const asset = res.assets[0];
  const base64 = await FileSystem.readAsStringAsync(asset.uri, {
    encoding: FileSystem.EncodingType.Base64,
  });
  const wb = XLSX.read(base64, { type: 'base64' });
  const firstSheet = wb.Sheets[wb.SheetNames[0]];

  // Try parsing with headers first
  const withHeaders = XLSX.utils.sheet_to_json<Record<string, unknown>>(firstSheet, {
    defval: '',
    raw: false,
  });
  let headers: string[] = [];
  let rows: Record<string, unknown>[] = [];
  let hasHeaders = false;

  if (withHeaders.length > 0) {
    const headerCandidates = Object.keys(withHeaders[0]);
    if (looksLikeRealHeaders(headerCandidates)) {
      headers = headerCandidates;
      rows = withHeaders;
      hasHeaders = true;
    }
  }

  if (!hasHeaders) {
    // Re-parse as array-of-arrays so we never depend on bogus header names.
    const arrayRows = XLSX.utils.sheet_to_json<unknown[]>(firstSheet, {
      header: 1,
      defval: '',
      raw: false,
    });
    if (arrayRows.length > 0) {
      const maxCols = arrayRows.reduce((m, r) => Math.max(m, r.length), 0);
      headers = Array.from({ length: maxCols }, (_, i) => `col_${i + 1}`);
      rows = arrayRows.map((row) => {
        const obj: Record<string, unknown> = {};
        for (let i = 0; i < maxCols; i++) {
          obj[`col_${i + 1}`] = row[i] ?? '';
        }
        return obj;
      });
    }
  }

  // Remove completely empty rows from the entire dataset
  rows = rows.filter((row) => {
    let filled = 0;
    for (const key of headers) {
      if (String(row[key] ?? '').trim().length > 0) filled++;
    }
    return filled > 0;
  });

  // For the AI preview, find rows with at least 2 filled columns (real data rows)
  const denseRows = rows.filter((row) => {
    let filled = 0;
    for (const key of headers) {
      if (String(row[key] ?? '').trim().length > 0) filled++;
    }
    return filled >= 2;
  });

  // Compact text preview (first 12 dense rows is enough for the AI to understand structure).
  const sourceRows = denseRows.length > 0 ? denseRows : rows;
  const sampleSize = Math.min(12, sourceRows.length);
  const sample = sourceRows.slice(0, sampleSize);
  const preview =
    `Columns: ${headers.join(' | ')}\n` +
    `Has real headers: ${hasHeaders}\n` +
    sample
      .map(
        (r, i) =>
          `Row ${i + 1}: ${headers.map((h) => `${h}=${String(r[h] ?? '').trim()}`).join(' | ')}`,
      )
      .join('\n');

  return { name: asset.name, rows, headers, hasHeaders, preview, totalRows: rows.length };
}
